# Generated by Django 3.2 on 2021-05-12 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='old', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(default='', max_length=150)),
                ('start_time', models.IntegerField(default=1620805435)),
                ('end_time', models.IntegerField(default=1620806035)),
                ('salt', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id', 'UserID', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('disease', models.IntegerField()),
                ('tobacco', models.IntegerField()),
                ('education', models.IntegerField()),
                ('score', models.IntegerField(default=0)),
                ('degree', models.CharField(max_length=15)),
                ('knowledge', models.CharField(max_length=10)),
                ('food', models.CharField(max_length=10)),
                ('sugar', models.CharField(max_length=10)),
                ('exercise', models.CharField(max_length=10)),
                ('prediction', models.CharField(max_length=10)),
                ('assess_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'age', 'gender', 'pressure', 'disease', 'tobacco', 'education', 'score', 'degree', 'knowledge', 'food', 'sugar', 'exercise', 'prediction')},
            },
        ),
    ]
