# Generated by Django 3.2 on 2021-05-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordchangerequest',
            name='end_time',
            field=models.IntegerField(default=1621690495),
        ),
        migrations.AlterField(
            model_name='passwordchangerequest',
            name='start_time',
            field=models.IntegerField(default=1621689895),
        ),
    ]
